### PR TITLE
Italian lang for calendar

### PR DESCRIPTION
**Pull request by brugnara**
Hi. Here's the it lang.  `.min.js` is missing.

Can you please tell me how you create it? If yes, I'll create by myself.

Also thanks for your great work on this and all the others Bulma modules! 👍

### CODE REVIEW

**Comment by Wikiki** [comment]
Thanks,

for the minified version I use the SASS plugin in Atom.
Feel free to generate it (I'm not at home so I'll not be able to do it until the ed of the month).

regards

**Comment by brugnara** [comment]
I mean the JavaScript min file. Does the SASS plugin build the JS too?

**Comment by Wikiki** [comment]
My bad, I use the google minify engine to generate (also as a plugin for atom)

**Comment by Wikiki** [comment]
I've updated the .min version.

**Pull request merged**
