### PR TITLE
add editTimeManually option 

### PR DESCRIPTION
**Pull request by miedzikd**
Hi @Wikiki ,

I have created this PR because to show solution for #238 issue

When you set `editTimeManually: true` then
- timepicker is working but is hiden
- time in header is editable

Results:
image

### CODE REVIEW

**Comment by miedzikd** [comment]
Hello @Wikiki  :) Im really happy when I see progress here :) 
If I can help somehow please tell me ;)

**Comment by Wikiki** [comment]
Hi,

could you please remove those files from your PR so I'll be able to merge it:


Conflicting files:
dist/js/bulma-calendar.js
dist/js/bulma-calendar.min.js
src/demo/assets/js/bulma-calendar.min.js

**Comment by miedzikd** [comment]
sure

**Comment by Wikiki** [comment]
Don't worry I'll integrate your change manually

**Comment by miedzikd** [comment]
hmm... I was trying remove this files... but this was solved problem only for one file... 
thanks for your help

**Comment by Wikiki** [comment]
Integrated in v6.0.8

**Pull request closed without merging**
