### PR TITLE
Fix issue when button without type="button' was trying to submit form

### PR DESCRIPTION
**Pull request by vladra**
When datepicker is placed inside of the form, every button press (cancel, reset, left, etc) is actually submitting the form. This happens because default type of the button is `submit`.

Adding `type="button"` avoids html to trigger submit.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

> submit: The button submits the form data to the server. This is the default if the attribute is not specified, or if the attribute is dynamically changed to an empty or invalid value.

### CODE REVIEW

**Comment by Wikiki** [comment]
Hi,

<code>type="button"</code> has already been added to the last sources.

**Comment by vladra** [comment]
@Wikiki hi
didn't notice that type statement, fixed

**Comment by khiet** [comment]
@vladra Nice work, @Wikiki could you merge this in?

**Comment by Wikiki** [comment]
The fix has been added to the v5.0.4 release

**Pull request closed without merging**
